# syntax = docker/dockerfile:1.2
FROM python:3.9-alpine3.12

RUN apk add --no-cache aws-cli

WORKDIR /usr/src/cdn-proxy
ENV PYTHONPATH /usr/src/cdn-proxy

# Install dev requirements
RUN apk add --no-cache \
    gcc \
    build-base \
    musl-dev \
    linux-headers \
    libffi-dev \
    openssl-dev \
    rust \
    cargo \
    make \
    bash \
    py3-cryptography

COPY ./requirements* ./
RUN python3 -m pip install -r requirements.txt -r requirements-dev.txt

COPY ./ ./

ENTRYPOINT ["sh", "-c"]
CMD ["bash"]
