on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: RhinoSecurityLabs/cdn-proxy@v0.1.0
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
